# This is a basic workflow to help you get started with Actions

name: python project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on'
    runs-on: ubuntu-latest

    # Enviroment variables
    env:
      global:
        PIPENV_VENV_IN_PROJECT: 1
        PIPENV_IGNORE_VIRTUALENVS: 1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.1'

      - name: install
        run: |
          pip install pipenv
          pipenv sync -d

      # Runs a set of commands using the runners shell
      - name: flake8
        run: |
          pipenv run flake8 .
